[package]
name = "vrc-get"
version = "1.1.1-SNAPSHOT"
edition = "2021"

license = "MIT"
authors = ["anatawa12 <anatawa12@icloud.com>"]
description = "Open Source command line client of VRChat Package Manager."
homepage = "https://github.com/anatawa12/vrc-get#readme"
repository = "https://github.com/anatawa12/vrc-get"
readme = "README.md"
keywords = ["vpm", "package-manager"]
categories = ["command-line-utilities"]

exclude = [
    ".github/**",
    ".cargo/**",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_zip = { version = "0.0.15", features = ["deflate", "tokio"] }
clap = { version = "4.3.8", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.28"
indexmap = { version = "1.9.3", features = ["serde"] }
itertools = "0.10.5"
log = "0.4.19"
pin-project-lite = "0.2.9"
reqwest = { version = "0.11.18", features = ["blocking", "native-tls-vendored", "stream"] }
semver = { version = "1.0.17", features = ["serde"] }
serde = { version = "1.0.164", features = ["derive", "rc"] }
serde_json = { version = "1.0.97", features = ["preserve_order"] }
sha2 = "0.10.7"
tokio = { version = "1.28.2", features = ["rt", "macros", "fs"] }
tokio-util = "0.7.8"
uuid = { version = "1.3.4", features = ["v4"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.48.0", features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_System_Com"] }
