[package]
name = "vrc-get"
version = "1.3.1-SNAPSHOT"
edition = "2021"

license = "MIT"
authors = ["anatawa12 <anatawa12@icloud.com>"]
description = "Open Source command line client of VRChat Package Manager."
homepage = "https://github.com/anatawa12/vrc-get#readme"
repository = "https://github.com/anatawa12/vrc-get"
readme = "README.md"
keywords = ["vpm", "package-manager"]
categories = ["command-line-utilities"]

exclude = [
    ".github/**",
    ".cargo/**",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_zip = { version = "0.0.15", features = ["deflate", "tokio", "deflate64"] }
clap = { version = "4.4.3", features = ["derive"] }
clap_complete = "4.4.1"
env_logger = "0.10.0"
futures = "0.3.28"
indexmap = { version = "2.0.0", features = ["serde"] }
itertools = "0.11.0"
log = "0.4.20"
pin-project-lite = "0.2.13"
reqwest = { version = "0.11.20", features = ["blocking", "stream"], default-features = false }
semver = { version = "1.0.18", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive", "rc"] }
serde_json = { version = "1.0.107", features = ["preserve_order"] }
sha2 = "0.10.7"
tokio = { version = "1.32.0", features = ["rt", "macros", "fs"] }
tokio-util = "0.7.8"
uuid = { version = "1.4.1", features = ["v4"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.51.1", features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_System_Com"] }

[patch.crates-io]
async_zip = { git = "https://github.com/Majored/rs-async-zip.git", rev = "a58024e" }

[features]
default = ["rustls"]
native-tls = ["reqwest/native-tls-vendored"]
rustls = ["reqwest/rustls-tls-native-roots"]
