[package]
name = "vrc-get"
version = "0.1.13-SNAPSHOT"
edition = "2021"

license = "MIT"
authors = ["anatawa12 <anatawa12@icloud.com>"]
description = "Open Source command line client of VRChat Package Manager."
homepage = "https://github.com/anatawa12/vrc-get#readme"
repository = "https://github.com/anatawa12/vrc-get"
readme = "README.md"
keywords = ["vpm", "package-manager"]
categories = ["command-line-utilities"]

exclude = [
    ".github/**",
    ".cargo/**",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_zip = { version = "0.0.11", features = ["deflate"] }
clap = { version = "4.1.6", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.26"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
log = "0.4.17"
pin-project-lite = "0.2.9"
reqwest = { version = "0.11.14", features = ["blocking", "serde_json", "json", "native-tls-vendored", "stream"] }
semver = { version = "1.0.16", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_json = { version = "1.0.93", features = ["preserve_order"] }
sha2 = "0.10.6"
tokio = { version = "1.25.0", features = ["rt", "macros", "fs"] }
uuid = { version = "1.3.0", features = ["v4"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.44.0", features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_System_Com"] }
