name: Publish to brew

on:
  workflow_dispatch:
    inputs:
      version:
        description: name of tag for this publish
        required: true
        type: string
  release:
    types: [published]

jobs:
  update-brew-repo:
    name: Publish to homebrew
    environment: 
      name: homebrew-core
      url: https://github.com/anatawa12/homebrew-core
    runs-on: macos-latest
    env:
      CLONE_TAP_TO: brew-tap
    steps:
      - run: git config --global user.name "github-actions[bot]" &&
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: update brew
        run: brew update && brew update

      - uses: actions/checkout@v3
        with:
          repository: anatawa12/homebrew-core
          path: ${{ env.CLONE_TAP_TO }}
          token: ${{ secrets.BREW_GITHUB_PAT }}

      - name: configure tap
        run: |-
          TAP_PATH="$(brew --repository "anatawa12/core")"
          mkdir -p "$(dirname "$TAP_PATH")"
          ln -s "$(readlink -f -- "$CLONE_TAP_TO")" "$TAP_PATH"

      - name: Create update pr for anatawa12/homebrew-core 
        env:
          VERSION: ${{ github.event.release.tag_name || inputs.version }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_GITHUB_PAT }}
        run: |-
          brew bump-formula-pr \
            anatawa12/core/vrc-get \
            --no-fork \
            --url "https://github.com/anatawa12/vrc-get/archive/${VERSION}.tar.gz"
